spring.application.name: api-gateway
server.port: 5555

# routes to serviceId
zuul.routes.api-a.path: /cloud-simple-service/**
zuul.routes.api-a.serviceId: cloud-simple-service

zuul.routes.api-b.path: /cloud-simple-serviceB/**
zuul.routes.api-b.serviceId: cloud-simple-serviceB

#zuul.routes.api-c.path: /cloud-simple-serviceC/**
#zuul.routes.api-c.serviceId: cloud-simple-serviceC

zuul.routes.api-ui.path: /cloud-simple-ui/**
zuul.routes.api-ui.serviceId: cloud-simple-ui

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring.zipkin.baseUrl: http://localhost:9411
spring.zipkin.enabled: true
spring:
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
      